---
- name: Install Zabbix and Grafana
  hosts: your_rhel_servers
  become: yes
  vars:
    zabbix_version: 5.4   # Adjust to the desired Zabbix version
    grafana_version: 8.0  # Adjust to the desired Grafana version

  tasks:
    - name: Install required dependencies
      package:
        name: "{{ item }}"
        state: present
      loop:
        - wget
        - curl
        - vim
        - epel-release
        - https://repo.zabbix.com/zabbix/{{ zabbix_version }}/rhel/7/x86_64/zabbix-release-{{ zabbix_version }}-1.el7.noarch.rpm
        - https://packages.grafana.com/oss/rpm/grafana-release-{{ grafana_version }}-1.noarch.rpm

    - name: Install Zabbix Server, Frontend, and Agent
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - zabbix-server-mysql
        - zabbix-web-mysql
        - zabbix-agent

    - name: Install MySQL/MariaDB client
      package:
        name: mysql
        state: present

    - name: Install Grafana
      package:
        name: grafana
        state: present

    - name: Start and enable Zabbix Server and Grafana services
      systemd:
        name: "{{ item }}"
        state: started
        enabled: yes
      with_items:
        - zabbix-server
        - zabbix-agent
        - grafana-server

    - name: Open port 80/tcp for Zabbix Web frontend
      firewalld:
        service: http
        permanent: yes
        state: enabled
        immediate: yes

    - name: Open port 3000/tcp for Grafana
      firewalld:
        port: 3000/tcp
        permanent: yes
        state: enabled
        immediate: yes

    - name: Display Zabbix initial admin password
      debug:
        msg: "Zabbix initial admin password: admin"

    - name: Display Grafana admin password
      debug:
        msg: "Grafana admin password: admin"

    # You may want to add additional tasks here for configuration or customization.